name = "Laplace's Blog"
license = "MIT"
licenselink = ""
description = ""

homepage = "https://haochen.info"

# demosite = "https://michaelneuper.github.io/hugo-texify3/"

# tags = ["blog", "clean", "latex", "light", "minimal", "responsive", "simple"]
# features = ["blog", "postcss", "comments", "google analytics"]

[author]
    name = "Hao Chen"
    homepage = "https://haochen.info"

[original]
    author = "Pavel Sapezhka"
    repo = "https://github.com/weastur/hugo-texify2"
    